FROM node:22.14.0

WORKDIR /app 

COPY package*.json ./

RUN npm install 

COPY . . 

ARG VITE_API_URL
ARG VITE_MAPTILER_KEY
ARG VITE_CLERK_PUBLISHABLE_KEY


ENV VITE_API_URL=$VITE_API_URL
ENV VITE_MAPTILER_KEY=$VITE_MAPTILER_KEY
ENV VITE_CLERK_PUBLISHABLE_KEY=$VITE_CLERK_PUBLISHABLE_KEY


RUN npm run build 

RUN npm install -g serve 

EXPOSE 5173 

CMD ["serve", "-s", "dist", "-l", "5173"]